name: Feature Request
description: Suggest an idea or enhancement for PandaBranchPlus
title: "[Request] "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Problem description
      description: Is your feature request related to a problem? A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when..."
    validations:
      required: false

  - type: textarea
    attributes:
      label: Proposed solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or features you have considered.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Screenshots, mockups, or any other context about the feature request.
    validations:
      required: false
