#!/usr/bin/env bash

# Description: Generate JavaScript API documentation (docs/api/javascript.md)
# using jsdoc-to-markdown.
# Behavior:
#  - Uses `jsdoc-to-markdown` (local `node_modules/.bin/jsdoc2md` or global
#    `jsdoc2md`).
#  - Accepts explicit file paths as arguments or scans
#    `octoprint_pandabranchplus/static/js/**/*.js`.
#  - Optionally offers to install `jsdoc-to-markdown` interactively in a TTY.
#  - Trims trailing whitespace from the generated Markdown output.
# Usage examples:
#  - ./scripts/generate-jsdocs.sh
#  - ./scripts/generate-jsdocs.sh octoprint_pandabranchplus/static/js/pandabranchplus.js

set -e

usage() {
cat <<'USAGE'
Usage: scripts/generate-jsdocs.sh [FILES...]

Generate JavaScript API documentation into `docs/api/javascript.md`.

If FILES are provided they are used as the input list; otherwise the script
scans `octoprint_pandabranchplus/static/js/**/*.js` for source files.

Options:
    -h, --help    Show this help message and exit

Examples:
    ./scripts/generate-jsdocs.sh
    ./scripts/generate-jsdocs.sh octoprint_pandabranchplus/static/js/pandabranchplus.js
USAGE
}

if [[ "${1:-}" = "-h" || "${1:-}" = "--help" || "${1:-}" = "help" ]]; then
        usage
        exit 0
fi

echo "Generating JavaScript API documentation..."

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." >/dev/null 2>&1 && pwd)"
JS_SRC_DIR="$PROJECT_ROOT/octoprint_pandabranchplus/static/js"
DOCS_API_DIR="$PROJECT_ROOT/docs/api"
OUTPUT="${DOCS_API_DIR}/javascript.md"

ARGS=("$@")
USE_PASSED_FILES=0
if [ "${#ARGS[@]}" -gt 0 ]; then
    USE_PASSED_FILES=1
fi

if [ "$USE_PASSED_FILES" -eq 1 ]; then
    missing=0
    for f in "${ARGS[@]}"; do
        if [ ! -f "$PROJECT_ROOT/$f" ]; then
            echo "Warning: passed file not found: $f" >&2
            missing=1
        fi
    done
    if [ "$missing" -eq 1 ]; then
        echo "Aborting jsdoc generation due to missing files." >&2
        exit 1
    fi
else
    if [ -z "$(find "$JS_SRC_DIR" -type f -name '*.js' -print -quit 2>/dev/null)" ]; then
        echo "Warning: No JavaScript files found"
        mkdir -p "$DOCS_API_DIR"
        printf '# JavaScript API\n\nNo JavaScript files found for documentation generation.\n' > "$OUTPUT"
        exit 0
    fi
fi

mkdir -p "$DOCS_API_DIR"

if [ -x "$PROJECT_ROOT/node_modules/.bin/jsdoc2md" ]; then
    JSDOC2MD="$PROJECT_ROOT/node_modules/.bin/jsdoc2md"
elif command -v jsdoc2md >/dev/null 2>&1; then
    JSDOC2MD="jsdoc2md"
else
    if [ -t 0 ]; then
        read -r -p "jsdoc-to-markdown not found locally. Install as dev-dependency now? (y/N) " REPLY
        case "$REPLY" in
            [yY])
                (cd "$PROJECT_ROOT" && npm install --save-dev jsdoc-to-markdown) || {
                    echo "Failed to install jsdoc-to-markdown" >&2
                    exit 1
                }
                JSDOC2MD="$PROJECT_ROOT/node_modules/.bin/jsdoc2md"
                ;;
            *)
                echo "jsdoc-to-markdown not installed; aborting documentation generation." >&2
                exit 1
                ;;
        esac
    else
        echo "jsdoc-to-markdown not found and session is non-interactive; aborting." >&2
        exit 1
    fi
fi

{
    echo "# JavaScript API"
    echo ""
    echo "<!-- Generated by scripts/generate-jsdocs.sh from JSDoc comments."
    echo "     Do not edit by hand. -->"
    echo ""
} > "$OUTPUT"

if [ "$USE_PASSED_FILES" -eq 1 ]; then
    if ! (cd "$PROJECT_ROOT" && "$JSDOC2MD" --configure "docs/jsdoc.json" "${ARGS[@]}" >> "$OUTPUT"); then
        echo "JSDoc generation failed" >&2
        exit 1
    fi
else
    if ! (cd "$PROJECT_ROOT" && "$JSDOC2MD" --configure "docs/jsdoc.json" "octoprint_pandabranchplus/static/js/"*.js >> "$OUTPUT"); then
        echo "JSDoc generation failed" >&2
        exit 1
    fi
fi

# trim trailing whitespace, portable across GNU/BSD sed
if command -v sed >/dev/null 2>&1; then
    if sed --version >/dev/null 2>&1; then
        sed -i -E 's/[[:space:]]+$//' "$OUTPUT" || true
    elif [ "$(uname -s 2>/dev/null)" = "Darwin" ]; then
        sed -i '' -E 's/[[:space:]]+$//' "$OUTPUT" || true
    else
        sed -i -E 's/[[:space:]]+$//' "$OUTPUT" || true
    fi
fi

echo "Generated $OUTPUT"
